### ISSUE TITLE
[API][validation] API側のバリデーションどこまでかけるか

### ISSUE THREAD

**Issue by Tchikawa** [hr-js/sta_access_manager#100]
必要最低限でいいのでは？ってなってます。
yyyyMMdd　->　\d{4}\d{1,2}\d{1,2} (From-Toの時系列は気にしない)
など

**Comment by ghost** [comment]
yyyymddやyyyymmdといった日付フォーマットは扱いたくないので、`\d{4}\d{2}\d{2}`で大丈夫です。

**Comment by ghost** [comment]
時系列は簡単にできるので気にしてください。

**Comment by Tchikawa** [comment]
了解です！ありがとう！
