### ISSUE TITLE
APIドキュメントの作成(Swagger)

### ISSUE THREAD

**Issue by krhrtky** [hr-js/sta_access_manager#114]
## 概要
- Wikiに書いていたAPIのendpointやparameter等を[Swagger](https://swagger.io/)で再作成する。

## 経緯
- APIの情報の更新漏れがあった。
- コードで管理できれば、更新履歴が分かる。

## 作成方法
- swagger editorをdockerで立ち上げて作成してpushする。
- ディレクトリ等は別途検討。

**Comment by krhrtky** [comment]
これができれば、手作業で書かなくてもいいのか...
https://github.com/fastify/fastify-swagger

**Comment by ghost** [comment]
@krhrtky 
全然違う話かもですが、flowtypeをAPI側にも導入していいのかなと思いました。

**Comment by krhrtky** [comment]
@kakaka19 
TypeScriptでなく？

**Comment by ghost** [comment]
@krhrtky 
どっちでもいいかな

**Comment by krhrtky** [comment]
@kakaka19 
リリース後のフェーズで考えよう
頭には入れとくくらいの感じで

**Comment by ghost** [comment]
@krhrtky 
Daoの方には導入しちゃっていいかな? 型=DBのスキーマみたいに考えられるから、実装楽になるんだよね(ドキュメンテーション関係ない話だし、優先度低いけど.)。

**Comment by krhrtky** [comment]
@kakaka19 
controllerを実装する中で考慮しないといけないところってある？
transpileしないといけないとか

**Comment by ghost** [comment]
@krhrtky 
その辺りはまだわかんない。ただcontrollerはschmeがもう定義されてるから、Daoだけ導入してもよさげな気もしてる。

**Comment by ghost** [comment]
https://dev.classmethod.jp/etc/lambda-node-js-flow-type-check/

babel入れるだけでいい感じなのかな...まぁ管理者の方の機能実装したら試しにやってみる。

**Comment by krhrtky** [comment]
管理者画面はべつissueで管理したほうがいいと思うので、一度クローズします。
