### ISSUE TITLE
APIのディレクトリ構成検討

### ISSUE THREAD

**Issue by ghost** [hr-js/sta_access_manager#115]
### 目的

API側のディレクトリ構成を検討しないまま進めてしまったため、ソースファイルの配置が機能に即しないものとなっている。実装/機能追加が進むと混乱の元になるため、再構成する

### 対象リポジトリ
https://github.com/hr-js/sam_api_server

**Comment by ghost** [comment]
現状
```
├── LICENSE
├── README.md
├── assetes
│   └── schema.js
├── package.json
├── routes
│   ├── provider.js
│   ├── query.js
│   └── users.js
├── server.js
├── test
│   └── ...
└── yarn.lock
```

**Comment by ghost** [comment]
- dao関係のファイル(provider.js,query.js)を `/routes`から`/infrastructure(新規で作成)`に移動
- `/assetes`がそもそもスペルミス(おそらくassets)、また、命名が機能に即していないため、`/schema`にリネーム。
- schema.jsが膨らんで来ているので、request.js、response.js、error.jsに分ける。(できれば)

**Comment by ghost** [comment]
こんな感じを想定
```
.
├── LICENSE
├── README.md
├── schema(/routesにいてもいいかもね)
│   ├── request.js
│   ├── response.js
│   └── error.js
├── infrastructure
│   ├── query.js
│   └── provider.js
├── package.json
├── routes
│   └── users.js(これも名前微妙な気がする)
├── server.js
├── test
│   └── ...
└── yarn.lock
```

**Comment by ghost** [comment]
@krhrtky 
検討案出しました。意見お願いします

**Comment by krhrtky** [comment]
@kakaka19 
個人的にはルートの配下に機能ごとのディレクトリを切ると見づらいのかなとおもいました。
javaだったりrailsのように src または app を作ってその中に各ディレクトリを作ったほうが見やすいかなと。
意図的にその構成にしなかった理由があれば聞いてみたいです。

あと、 `infrastructure` は配下の中身が想像しにくいかなとも思いました。

一応、自分の素案を載せておきます。
```
├── __test__
│   ├── controller
│   └── repository
└── app
    ├── commons
    │   ├── enums
    │   └── schemas
    ├── controllers
    └── repositories
```

**Comment by ghost** [comment]
@krhrtky 
>javaだったりrailsのように src または app を作ってその中に各ディレクトリを作ったほうが見やすいかなと。
意図的にその構成にしなかった理由があれば聞いてみたいです。

そこまでの量じゃないかなーと思って切ってなかったですが、直下にあると面倒かもしれませんね。賛成です。

>あと、 infrastructure は配下の中身が想像しにくいかなとも思いました。

`/repository`でも`/dao`でもよかったんですが、リクエストに関係ない起動時の疎通確認処理などが入るので、少し包括的な名前にしました。ただ、`/repository`にしてその下に`/infrastructure`切ってもいいですね。

素案についてですが、ディレクトリ名は複数形にしなくていいと思います。アプリケーション内での役割を示せればいいので。他の細かい疑問は下に書いています。
```
├── __test__(この表記よく見ますけどアンダーバー必要なんですかね？)
│   ├── controller(ディレクトリ名はapp下と合わせた方がいいのでは？)
│   └── repository
└── app
    ├── commons
    │   ├── enums(どのようなファイルが置かれるイメージですか？)
    │   └── schemas(controllerでのみ使用されると思うので、commonにいるのは間違いでは？)
    ├── controllers
    └── repositories
```

**Comment by ghost** [comment]
`/infrastructure `じゃなくて`/init`とか`/boot`とかのがわかりやすいかもしれないですね。`/repository`とは別にして

**Comment by ghost** [comment]
@krhrtky 
まとめると、こんな感じがいいような。
```
├── test
│   ├── controller
│   ├── repository
│   └── init
└── app
    ├── common
    │   └── enum(要不要は置いといて)
    ├── controller
    │   └── schema
    ├── repository
    └── init
```

**Comment by krhrtky** [comment]
> そこまでの量じゃないかなーと思って切ってなかったですが、直下にあると面倒かもしれませんね。賛成です。

ひとまずここのディレクトリは決定で。

initって何をやるものなんだっけ？

**Comment by ghost** [comment]
appの起動時にElasticsearchが立ち上がっているかを確認したりとか、その日の入退室情報を記録するインデックスを作成したりとか、要は起動時に必要な諸々の処理。`/infrastructure`にしようかと思ったけどわかりづらいから`/init`にした。

**Comment by ghost** [comment]
@krhrtky mentionつけ忘れ

**Comment by krhrtky** [comment]
それだったら、ウェブアプリを確認する機能だから、
appのディレクトの外においたほうがよくないかな？

**Comment by krhrtky** [comment]
`__test__` はjest使ってるので見るかなと
`__mock__` と同じように表現を合わせているんじゃないかな。

**Comment by krhrtky** [comment]
`__test__` の配下は `app` と同じディレクトリ名の認識であってます(直し漏れ)です。
`enums` の名前は変えてもいいと思っているんだけど、
purposeとか固定値を管理する場所にしたい。
`provider.js` に直にかいてあるのは見たのだけれど、それだと管理できないと思ったので。

**Comment by ghost** [comment]
@krhrtky 
>それだったら、ウェブアプリを確認する機能だから、
appのディレクトの外においたほうがよくないかな？

一応dockerコンテナで動かすことを考えると、アプリ自体にその疎通確認の機能は必要だから`/app`下に置いた方がいいかなと思う(このアプリの機能ですっでのを示すためにも)。

>__test__ はjest使ってるので見るかなと
__mock__ と同じように表現を合わせているんじゃないかな。

アンダーバー必要なかったらない方がいいかな。cdとか設定ファイルでディレクトリ指定するときめんどい。

>__test__ の配下は app と同じディレクトリ名の認識であってます(直し漏れ)です。enums の名前は変えてもいいと思っているんだけど、purposeとか固定値を管理する場所にしたい。provider.js に直にかいてあるのは見たのだけれど、それだと管理できないと思ったので。

それならおけです。

**Comment by krhrtky** [comment]
> このアプリの機能ですっでのを示すためにも

それはgitのリポジトリの中で管理しているからアプリの一部として認識できるんじゃないかなと思うけど、それとは考え方的に違うかな？

testディレクトは特にこだわりないので `test` でOKです。

**Comment by krhrtky** [comment]
## 残課題

- あとはどの段階で変更するか

- 今のPRをどうするか

**Comment by ghost** [comment]
>それはgitのリポジトリの中で管理しているからアプリの一部として認識できるんじゃないかなと思うけど、それとは考え方的に違うかな？

ほかのソースはapp下にいるのにそこだけルート直下ってのも変じゃない？
あとdockerコンテナで動かすときに/appにいると都合がいいってのもある。

今のPRが消化したらでいいんじゃないかな。それまでissueは開いておこう

**Comment by krhrtky** [comment]
@kakaka19 
若干詰まってない状態で進めてしまった部分があったと感じた。
- `app.js` はエントリーポイントになるのでappディレクトリ直下でいいと考えています。
- initディレクトリは中身ができるときに追加。
- schemaはcommonsにするって頭になってたのでcontollersに移動します。

**Comment by ghost** [comment]
@krhrtky 
ディレクトリ名は複数形である必要はないので、単数形にしてください

**Comment by krhrtky** [comment]
@kakaka19 
特に主義はないので、変更します。
何かの構成を参考にした感じですか？

**Comment by ghost** [comment]
@krhrtky 
何かの構成を参考にしたというより、そもそも複数形でつける必要がないかなと。

**Comment by krhrtky** [comment]
@kakaka19
了解です

**Comment by ghost** [comment]
@krhrtky 
closeしていい？

**Comment by ghost** [comment]
mergeされたためclose
