### ISSUE TITLE
ICカード読み取り時に出力する音声を検討する

### ISSUE THREAD

**Issue by kakaka19** [hr-js/sta_access_manager#13]
ICカード読み取り時に人ごとに異なる音声が出力したい。

実装・設計はスコープ外。**誰の**ICカードを読み込んだ時に、**どの音声/音源**を出力するかを決定して欲しい。

せっかくなので、色々な背景を気にせずに自由に検討していただきたいです。

**Comment by ikkyu-3** [comment]
## ぱっと思いついたもの
### 登録されていないICカードを読み込んだ時
* 音声なら「このICカードは登録されていません。」というアナウンス。音ならエラー的な音かなー
### デフォルト音源
* どっかで聞いたことのあるような音がいいなー。直感的
### カスタム音源
* ある程度音源や音声を用意しておいて、自分用にカスタムできるとおもしろいかも。
### ユーザー提供
* やはり自分でききたい音声があるはずと思うので、こういうのあるとテンション上がりますね。笑

**みなさんはどうでしょうか？**

**Comment by ghost** [comment]
都度検討する
