### ISSUE TITLE
利用者登録画面のプロトタイプを実装する

### ISSUE THREAD

**Issue by kakaka19** [hr-js/sta_access_manager#14]
[Raspberry Pi RASPBERRYPI-DISPLAY](https://www.amazon.co.jp/Raspberry-Pi-RASPBERRYPI-DISPLAY/dp/B0155WN7CK/ref=pd_bxgy_147_img_2?_encoding=UTF8&psc=1&refRID=BJBYXGMN88P9QRXKSV4J)とRaspberry 3は連携できたので、利用者の登録画面は実装することができる。

ただ、現段階では利用者情報の要不要が明確になっていない。プロトタイプを作成することで、仕様/詳細設計が見えてくるはず。

expressを利用したコーディングに慣れる事も含め、利用者登録画面のプロトタイプを実装してほしい。

**Comment by kakaka19** [comment]
@toyoshimmer 
@ikkyu-3 
プロトタイプの実装issueを勝手に作成してしまいましたが、色々と決めておいた方がいい事もあると思いますので、一度時間をとって話し合った方がいいかもしれないですね。

**Comment by ikkyu-3** [comment]
別のIssueで対応します。
