### ISSUE TITLE
Milestoneを作成する

### ISSUE THREAD

**Issue by kakaka19** [hr-js/sta_access_manager#16]
**課題把握**と**issueの見直し**を目的としてMilestoneを使用したい。進捗管理を行うにあたっても便利な機能だが、厳密にリリース日が決まっていないので、主目的ではない。

MIlestoneを使用し、issueの進捗を把握することで以下のメリットがある
- ある人がハマってしまっている課題に対し、他の人が解決方法を提示できる。
- 残存issueに着手しやすくなる。
- issueの把握にいちいち集まる必要がなくなる
- 消化できないissueに対し、適切な期限を再検討できる

**Comment by ikkyu-3** [comment]
## Milestone候補
* 開発準備
* 要件定義
* テスト実装
* 設計
* 運用
* 開発
* テスト
* リリース準備

こんな感じでどうでしょうか？
テスト実装は本当にその機能を実現できるのか的な意味合いです。プロトタイプ的なイメージ。
とりあえず、あげてみました。

**Comment by ikkyu-3** [comment]
2つにします。

### Preparation  
開発準備フェーズ 例: 仕様決め, 環境設定, 設計, 調査

### Development
開発フェーズ 例: 開発、モック開発、仕様や機能の問題提起など
