### ISSUE TITLE
サーバを運用するあたって、どういった設定が必要か検討する。

### ISSUE THREAD

**Issue by kakaka19** [hr-js/sta_access_manager#17]
自由に設定/使用できるサーバがあるので、有識者の意見を伺いつつ、サーバの設定を行う。

現時点(2017/10/14)ではElasticsearchを導入し、DBサーバとして運用することが決まっている。しかし、他のプロジェクトでも使用するので、互いに影響することがないようにしたい。

OSはUbuntuをインストールしているが、もしかすると仮想マシンホストとして運用し、プロジェクト毎にインスタンスを作成した方がリソースを気にせずに済むかもしれない。

**Comment by ikkyu-3** [comment]
別リポジトリに以降したためClose
