### ISSUE TITLE
javascriptやExpressにおけるTipsを書いていく

### ISSUE THREAD

**Issue by kakaka19** [hr-js/sta_access_manager#19]
javascriptのコーディングや、Expressの使い方など、各自気づいたことや、教えてもらったことをコメントに追加していく。いくつかまとまったらwikiを作成していく。

javascript 

- node.js 7系からclassが定義できるようになったので、`prototype`よりも`class`を使った方が良い。

参考：ES2015のnode.js対応状況 http://node.green/

**Comment by toyoshimmer** [comment]
javascript

- Setterを用いる場合、別名の変数に値を保存しないとSetterが無限に再帰的に呼び出されてしまい、`Maximum call stack size exceeded`エラーが発生してしまう。

悪い例
```var man = {
  get age() {
    return this.age;
  },
  set age(val) {
    this.age = val;
  }
};
```

良い例
```var man = {
  get age() {
    return this.age;
  },
  set age(val) {
    this._age = val;
  }
};
```

参考：https://qiita.com/hosomichi/items/c7d3cae7884a5e12a064

**Comment by ghost** [comment]
あんまり機能してないのでクローズしてもいいですかね。

**Comment by ikkyu-3** [comment]
全然機能してないから、いいと思います。

**Comment by krhrtky** [comment]
良いと思います

**Comment by ghost** [comment]
close!
