### ISSUE TITLE
[Low Priority] Node.jsのバージョンの統一

### ISSUE THREAD

**Issue by krhrtky** [hr-js/sta_access_manager#22]
### 現状
* user : pi
* 実行方法によって、異なるバージョンのNode.jsが、動作する環境になっている(以下参照)。

  ```sh
  $ node  # 8.x系
  ```
  ```sh
  $ sudo node # 0.1x系
  ```
### 統一する理由
* 今のところ、 `node` のみの使用なので問題はない。

* 今後、思わぬところで動かなくなって手が止まるのを避けたい。

### 対応案
* いずれかの方法で対応を検討。
  1. `/usr/bin` 配下にある 0.1x系 をアンインストール
  1. `/usr/bin/node` にnvmで選択しているバージョンのディレクトリを参照するようにシンボリックリンクを張る

### タイミング
* 手すき、息抜き程度でいいかと思います。

**Comment by ghost** [comment]
最新バージョンnode.js v9.4.0に決定
