### ISSUE TITLE
ローカルPCにテスト環境を構築する

### ISSUE THREAD

**Issue by kakaka19** [hr-js/sta_access_manager#23]
### 目的
ローカルPCにテスト環境を構築する。

### 規定事項
|事項|値|
|---|---|
|仮想OS|Ubuntu|
|DB|Elasticsearch|
|実行環境|Docker|

### ゴール
- 手順をwikiに記載

**Comment by kakaka19** [comment]
dockerはOSの選択ができない。

**Comment by kakaka19** [comment]
ローカルPCに仮想マシンを立てて、dockerを導入。vagrantを使えば共有も簡単。

**Comment by kakaka19** [comment]
Docker Hubを使えばコンテナごとデプロイすればいい。

https://hub.docker.com

**Comment by ikkyu-3** [comment]
JSON Serverで対応するのでClose
