### ISSUE TITLE
画面のプロトタイプ実装

### ISSUE THREAD

**Issue by minako-nakanishi** [hr-js/sta_access_manager#25]
モックができたので、プロトタイプを実装する。
それを元に画面側の検討を行う。

**Comment by minako-nakanishi** [comment]
プロトタイプ実装後、
@Tchikawa にレビューしてもらう。

**Comment by ikkyu-3** [comment]
画面ごとにissueを作成しました。今後はそちらで対応します。
よって、このissueはcloseさせてもらいます。
