### ISSUE TITLE
【モック】ユーザID入力画面の作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#31]
共有したキー入力画面(モック)の作成をお願いします。
モックなので、まずは、htmlとcssで作成してみてください。

以下のことを考えて実装してもらえるといいかと思います。
- ~~inputタグを使用しない方法で実装~~ 
- 足りないキーを作成

対応が遅くなるかもしれなですが、サポートしますのでよろしくお願いします。

**Comment by ikkyu-3** [comment]
## 目標
モックを作成後、番号を押したらテキストボックスに番号を表示するところまでで大丈夫です!

**Comment by minako-nakanishi** [comment]
承りました！

**Comment by minako-nakanishi** [comment]
番号ボタンの配置でtableタグを使おうかと思っているのですが、tableタグっであまり使わない方が良いんでしたっけ？
Pタグでも良いかなと思ってはいるのですが。。

**Comment by ikkyu-3** [comment]
> 番号ボタンの配置でtableタグを使おうかと思っているのですが、tableタグっであまり使わない方が良いんでしたっけ？
Pタグでも良いかなと思ってはいるのですが。。

pかtableかというと、pは使わないですね。↓ここみると、使用しないかなと、、、
[p 要素 - HTML | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/p)

グリッドレイアウトを使うときれいに配置できると思います。
[CSS グリッドレイアウト - CSS | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Grid_Layout)

グリッドレイアウトって検索するとわかりやすく説明してくれてるサイトいっぱいあるので、
一度検索してみてください。

**Comment by minako-nakanishi** [comment]
ありがとうございます！

**Comment by ikkyu-3** [comment]
[ユーザのマスターデータに関して](https://github.com/hr-js/sta_access_manager/issues/43)
案2を採用することになったので、こちらのモックは作成しないことに変更します。

よってcloseします。
