### ISSUE TITLE
【モック】目的選択画面の作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#33]
共有した選択一覧画面(モック)の作成をお願いします。
モックなので、htmlとcssで作成してみてください。

以下のことを考えて実装してもらえるといいかと思います。
- CSS Grid Layoutを使ってみましょう
- positionプロパティを意識してみてください

目的の色は指定があります。
共有フォルダの画面に、色を決めた時の画像ファイルがあるので、そちらで確認してください。

対応が遅くなるかもしれなですが、サポートしますのでよろしくお願いします。

**Comment by Tchikawa** [comment]
作成完了いたしました
https://github.com/Tchikawa/html_test/tree/master/select

**Comment by ikkyu-3** [comment]
現在レビュー中です。
画面はほぼほぼ完成段階にあります。少し修正してもらったりと、対応してもらっている状況です。

**Comment by Tchikawa** [comment]
マージが完了したためcloseします
