### ISSUE TITLE
ドキュメントの運用ポリシーを定める

### ISSUE THREAD

**Issue by ghost** [hr-js/sta_access_manager#42]
目的
---
ドキュメントの運用ポリシーを作成し、[wiki](https://github.com/hr-js/sta_access_manager/wiki)に記載する。

背景
---
ドキュメントの運用を、githubのwikiで行うことが決定した。#35
よって以下のことを定める。
- 記載してはいけないもの。
- 仕様/設計などのレビューフロー

ゴール
---

- [x] wikiに記載してはいけないものを明文化する
- [x] ドキュメント更新の際のフローを明文化する
- [x] 上記の二つに関してレビューを受け、項目の過不足を修正する
- [ ] 制定したポリシーをwikiに記載する

**Comment by ghost** [comment]
追加

レビューが必要/共有事項がある場合は、関係者をAsigneeに追加する

**Comment by ghost** [comment]
## wikiに記載するべきではない情報
### 個人情報
- 氏名
- 社内メールアドレス
- 社員番号

## ドキュメント更新のフロー
1. 作成するドキュメントに関してのissueを作成する
    - 自身とレビュワーをAsigneeにする。見ておいてほしい人もAsigneeに追加する。
    - 最低限そのドキュメントを作成する __目的__ はdescriptionに記載しておく
1. issueのコメントにドキュメントを書いていく(wikiはブランチが切れないため)
1. レビューを受ける/内容を修正する。
    - wikiのどこに書いたら良いか迷ったらこの時点で相談する
1. wikiに内容を反映する。

**Comment by ghost** [comment]
@ikkyu-3 
@krhrtky 

すっかり忘れていたこのissueを今更やりました。時間あるときにレビューお願いします。

**Comment by ikkyu-3** [comment]
@kakaka19 
確認しました。

> issueのコメントにドキュメントを書いていく

これいいっすね！

wikiに記載するべきではない情報・ドキュメント更新のフロー問題ないと思います。

**Comment by ghost** [comment]
@ikkyu-3 

ブランチ切ってプルリク出せればいいんですけど。苦肉の策すね...

**Comment by ikkyu-3** [comment]
@kakaka19 
とりあえず、これで運用してみて改善点あれば変えていきましょ

**Comment by ghost** [comment]
wikiに記載したのでクローズ(忘れていた)
