### ISSUE TITLE
【モック】TOP画面(待ち受け)の作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#44]
## モック作成
TOP画面(待ち受け)の作成をお願いします。

### 目標
画面を作成して、
ボタンを押して各画面名のアラートを表示するところまでとします。

**Comment by Tchikawa** [comment]
@ikkyu-3 
ボタンの作成と、ボタンのサイズ調整をしました。
お時間ある時にレビューをお願いいたします。
https://github.com/Tchikawa/html_test/tree/master/index

**Comment by ikkyu-3** [comment]
@Tchikawa 
作成ありがとう！
レビューします。少々おまちを

**Comment by ikkyu-3** [comment]
@Tchikawa 
補足です。この画面はテンプレートが使用できる画面ですが、
適用しなくて大丈夫です。後出しで作ったテンプレートなので、、、

**Comment by Tchikawa** [comment]
マージが完了したためcloseします
