### ISSUE TITLE
【モック】ユーザ未登録表示画面の作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#45]
## モック作成
ユーザ未登録表示画面の作成。

### 問題点
戻るボタン or ユーザ登録ボタンを追加する必要があります。

### 目標
画面を作成して、
~~もどるボタンを押してアラートを表示するところまでとします。~~ アラート表示は実装しない。

**Comment by Tchikawa** [comment]
完了したのでclose...??

**Comment by ikkyu-3** [comment]
@Tchikawa 
> 完了したのでclose...??

はい！確認したので、closeします。遅くなってしまって申し訳ない。
お疲れ様でした！
