### ISSUE TITLE
【モック】目的選択後画面の作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#47]
## モック作成
目的選択後の画面作成をお願いします。

### 目標
- 勉強会
- 仕事
- 自習
- 遊び
の４画面を作成し、

各TOP画面にもどるボタンを作成する。ボタンを押下すると「TOP画面へ」とアラートを表示するところまでとします。

**Comment by Tchikawa** [comment]
マージしたため、closeします。
