### ISSUE TITLE
【モック】退出時の表示画面の作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#48]
## モック作成
退出処理後の画面作成をお願いします。(現在作成されてないのでデザインも作成)

### 目標
画面を作成し、TOP画面に戻るボタンを作成する。
~~ボタンを押下すると「TOP画面へ」とアラートを表示するところまでとします。~~ アラート表示は実装しない。

**Comment by Tchikawa** [comment]
レビューしていただく

**Comment by ikkyu-3** [comment]
mergeしたのでcloseします。
