### ISSUE TITLE
【モック】ユーザ登録失敗画面の作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#52]
## モック作成
ユーザ登録失敗画面の作成

### 目標
画面を作成する。
~~ボタンを押してTOP画面とアラートを表示するところまでとします。~~ アラート表示は実装しない。

**Comment by minako-nakanishi** [comment]
吹き出しはCSSで作成するのでしょうか？

**Comment by ikkyu-3** [comment]
はい、cssで作成お願いします。

**`css バルーン表示`** で検索するといいかもです。

**Comment by Tchikawa** [comment]
[メモ]プルリク投げてる中です

**Comment by ikkyu-3** [comment]
mergeしたのでcloseします。
