### ISSUE TITLE
【モック】ユーザネーム入力画面の作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#54]
### 背景
[ユーザのマスターデータに関して](https://github.com/hr-js/sta_access_manager/issues/43)
~~案2を採用するので~~
「ユーザID入力」 => 「ユーザネーム入力」に変更となりました。
【追記】
案3を採用することに変更しました。
それに伴い、新規でユーザネーム入力画面の作成が必要となりました。

### 入力方法
**キーボードで入力してもらう**予定です。

### 作成手順
1. 画面デザインを作成
1. モックを作成

以下のような手順で作成します。
この機能が欲しいなど提案あれば、相談しましょう。

**Comment by Tchikawa** [comment]
レビューしていただく

**Comment by ikkyu-3** [comment]
mergeしたのでcloseします。
