### ISSUE TITLE
目的の選択肢についての提案

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#57]
### 現在の目的一覧
- 勉強会
- 仕事
- 遊び
- 自習

### 提案内容
「遊び」  =>  「サークル」

**サークル目的で使用する可能性がある**かなって思いまして、提案しました。
影響範囲は、URLの変更とモック、サーバは影響範囲なしです。

よろしくお願いします。

**Comment by Tchikawa** [comment]
いいと思います！！
[メモ]
・選択画面変更
・選択後画面変更
・人形のイラスト変更
・選択画面の設計書修正
・選択後画面の設計書修正

**Comment by ikkyu-3** [comment]
サークルに変更します。

**Comment by ghost** [comment]
サークル活動の方がいいんじゃないですが？

**Comment by ikkyu-3** [comment]
> サークル活動の方がいいんじゃないですが？

他の目的の文字数との差を小さくしたいという考えが実はありまして。。。

**Comment by krhrtky** [comment]
@ikkyu-3 
ふと思いましたが、

> 勉強会

勉強のほうがよくないですか？普通に勉強しに来てる人もいると思うし。

**Comment by ikkyu-3** [comment]
@krhrtky 
> 勉強のほうがよくないですか？普通に勉強しに来てる人もいると思うし。

`勉強会 => 勉強` と変更すると、
`自習` と`勉強` の違いが曖昧になってしまい、選択する人が困ってしまう心配があります。

もし`勉強` に変更した方がいいなら、自習をやめて、新たに目的を追加したほうがいいかもなって思っています。

**Comment by krhrtky** [comment]
@ikkyu-3 
すいません、自習見落としてました。
スルーしてください。

**Comment by ikkyu-3** [comment]
@krhrtky 
了解！

**現在の目的一覧**で、勉強会の下に自習って書いておけばよかったと思ってます。
一番下に書くのは、ちょっと自分の配慮足りてなかったかなって。
こちらも気をつけます！

**Comment by ikkyu-3** [comment]
`サークル` or `サークル活動` に関しては、

今後変更が容易に可能なので、暫定として`サークル` とさせてください。

すみませんがよろしくお願いします。

ということで、closeします。
ご意見ありがとうございました。
