### ISSUE TITLE
[2/4中必須]1st itelation の進捗状況確認

### ISSUE THREAD

**Issue by krhrtky** [hr-js/sta_access_manager#62]
## 目的

- 1/27にMilestoneに各自のissueを割り振った

- 各Itelationは２週間単位のMilestoneになるため、進捗を1週終了後に実施を決定

- まず、[1st Itelation](https://github.com/hr-js/sta_access_manager/milestone/3) について状況確認をしたい

## 確認項目

- 各自の進捗率(%)

- 完了目処

- タスクの消化が難しい場合のヘッジ方法(Milestoneの変更、Assigneesの変更 等)

- その他問題等

各自の状況について共有をお願いします。

Slackでのやり取り・決定事項も流れてしまうので、こちらに改めて残すようにしてください、

**Comment by ghost** [comment]
elasticsearchとの接続モジュール実装中です。イテレーション内で完了予定。

**Comment by Tchikawa** [comment]
モック4/13画面完了(30%)です。今日+2画面作成予定です。(50%)
オンスケです。

**Comment by ikkyu-3** [comment]
【Rasberry Pi側】wikiページ作成中です。
- 進捗率：80%(気持ちは2%)
- 完了目処：画像はモックが完成したらになりますが、他の情報は記述しておくので終わる見込みです。
- 問題：特になし

**Comment by nekonogeboku** [comment]
進捗率：50%
・画面設計機能草案作成済(ラフ)
残：今週中にまとめ→レビュー
今週中にレビューまで終了予定です。

**Comment by krhrtky** [comment]
回答ありがとうございます。

@kakaka19 
APIサーバ側は今Milestoneとかやってないけど、やったほうがいいだろうか？
管理画面は @Tchikawa  が担当してくれるそうなので、人数も増えたら必要かなと思った。
やるならこちらのrepositryのItelationにいれるのでもいいかな。

みなさん
オンスケで進んでいて良かったです。
このあたりから2nd Itelationを意識していきましょう。

次のスプリントのタスクの重さに問題ないでしょうか？
前もって多いなと感じていたら、早めに相談しましょう。

**Comment by ghost** [comment]
@krhrtky 

 人数少ないから必要ないかな。あってもいいけど、3人くらいなら直接やり取りした方が早い

**Comment by minako-nakanishi** [comment]
私の担当していたチケットは不要となったので、今は無職です。

**Comment by krhrtky** [comment]
@kakaka19  (cc: @Tchikawa )
了解！じゃあ口頭確認して、それをissueなりwikiに落とすカタチで！ 

@ikkyu-3 
1st Itelationしか見てなかったんですけど、次のタスクって各々見えているんでしょうか？

2nd Itelationが始まってから考えるのも時間もったいないかなと思ったんですが。

**Comment by krhrtky** [comment]
@minako-nakanishi 
今後はどんな予定なんだろう。

例えば、Reactの実装に向けての準備とか？

**Comment by ikkyu-3** [comment]
@krhrtky 
> 次のタスクって各々見えているんでしょうか？

自分の今後の予定としては、
- 環境構築(あと少し)
- ラズパイ側(node.js)の実装
- ディレクトリ構造を決める
- モックからコンポーネントを設計していく
- Presentational Components作成(jsx)
- Container Components作成
- action作成
- reducer作成
- 非同期処理(saga)作成
- テスト

って感じで進めていく予定です。

@tankette148 の次のタスクに関しては、細かく本人と話し合って決めているので大丈夫。
@Tchikawa の次のタスクは、API側の管理者の予定でよかったんでしたっけ？なのでモックまでは把握しています。
@minako-nakanishi の次のタスクは、Presentational Components作成(jsx)してみる？って感じで話をしている段階です。進捗見てタスク振れるとは思いますが、絶対振れる保証ができそうにないのが申し訳ない。2nd Itelationまでに[QUICK START](https://reactjs.org/docs/hello-world.html) がやれていれば、Presentational Components作成タスク振れる予定です。

**Comment by minako-nakanishi** [comment]
そもそもなんで、社員ID入力画面なくなったの？

**Comment by ghost** [comment]
@minako-nakanishi 
最初は多部署から社員ID+社員名のデータをもらおうと思っていたけど、セキュリティ的に難しくてもらえない＆もらうのに時間かかりそう

だから、ICカードID＋社員名+社内メールアドレスとかで管理することになった。ので、社員ID入力画面はなくなっちゃった。

**Comment by minako-nakanishi** [comment]
@kakaka19
自分で入力するからデータもらわなくても良いんじゃないの？

**Comment by ghost** [comment]
@minako-nakanishi 

もともと、社員IDを入力させるのは社員名と紐づいているから便利だねって話だった。でも、社員IDと社員名が紐づいているデータをもらえるかわからなくなったから、社員IDを入力させるメリットもなくなった。

まぁここに色々な経緯が載ってるからみてみてよ。
https://github.com/hr-js/sta_access_manager/issues/43

**Comment by krhrtky** [comment]
確認用につきclose
