### ISSUE TITLE
【Rasberry Pi側】wikiページ作成

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#63]
## 作成するもの
- 画面遷移図
- 各画面設計
    - 画面名
    - モック画面のキャプチャ
    - ~~機能(あれば)~~
    - 処理の説明やイベント(クリックなど)の説明

**Comment by ikkyu-3** [comment]
@Tchikawa @tankette148 @minako-nakanishi @krhrtky @kakaka19 @yumtana2 
Rasberry Pi側のwikiページ作成しました。確認してみてください。
何かあれば、ご意見よろしくお願いします。

今後変更など出てくるかと思いますが、随時更新していきます。

**Comment by ikkyu-3** [comment]
共有が確認できたらcloseします。

**Comment by ikkyu-3** [comment]
## レビュー
- ユーザ登録した後に、待ち受けに遷移せず、目的選択画面に遷移させたほうがいい
- ICカードの読み取りエラーを考慮されていない
- 入力チェックを考慮する
- email, name入力画面一緒でいいのではないか？
- 色がチカチカしそう
- 登録はキャンセルボタンがほしい
- 入力確認のダイアログがみえた方がいい
- 登録画面は1urlで対応する方がいい
- エラーのURLは`機能名/error` にする
- スキャンしてサーバが入退室を判断する
- 入退室にスイッチを表示させると変更できると思ってしまうのではないか？
- 参加者一覧に、現在いる人と今日いた人を表示できるようにしたい

**Comment by Tchikawa** [comment]
たしかに、Email、name一緒でいいですね...

**Comment by ikkyu-3** [comment]
- ラズパイで遷移できるモックを開発が必要

**Comment by ikkyu-3** [comment]
[Raspberry Pi側](https://github.com/hr-js/sta_access_manager/wiki/Raspberry-Pi%E5%81%B4)

- 画面遷移図更新しました。

【モック】モックアプリ作成 #73
でまた変更となる可能性が高いため、画面遷移図更新までとします。

closeします。
