### ISSUE TITLE
[モック] 背景の色を決める

### ISSUE THREAD

**Issue by Tchikawa** [hr-js/sta_access_manager#65]
それぞれの画面の背景色を決める。
急ぎでない

**Comment by ikkyu-3** [comment]
2nd iterationが終わるまでに、できれば決めていただきたいのですが、どうでしょうか。
3rd iterationから画面の実装を開始したいと考えてます。その辺相談できればと思っているので、よろしくお願いします。

**Comment by Tchikawa** [comment]
承知しました！！
ちょっときまっていて、原色がいいかなと思ってます！
・基本、green yellowでいいかなとおもってます。
・red、blue、yellow、pink、orange、deepskyblteらへんあとで割り振ります。

**Comment by Tchikawa** [comment]
原色系の方がいいかなと思っていましたが、実際に動かしてみて、
目的選択後の画面は、目的選択画面で決めたそれぞれの色と同じ(今のまま)で！！
読み取りエラー：red
お疲れ様でした：blue
ユーザー未登録：yellow
残り：green yellow
でお願いします。

**Comment by ikkyu-3** [comment]
closeしてなかったので、closeします。

コンポーネントができたらまた、レビューしましょう。
