### ISSUE TITLE
Reactのキャッチアップ

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#67]
## 背景
今後の実装を考えると、Reactがわかる人が欲しい。

## 今後任せたいタスク
まずはPresentational Components作成(jsx)をお願いしたい。
他もできるならどんどんお任せします。

## このissueの目標
Reactの理解を深めて、実装できるようになってもらいたい。

## どうやってやるの？
- [QUICK START](https://reactjs.org/docs/hello-world.html)を一通りやる。
- 余力あればReactの本を読み切る。

期限内に終って余裕があれば、どんどん理解を深めてもらいたい。(FluxとかReduxとか)

## 不明点が出た場合、まず意識してもらいたいこと(これは必須ではなく、推奨)
1. 何がわからないか把握する(メモをとる)
1. 色々とググってみる
1. それでもわからない時、質問する(どこまでやった or 調べたのか、ヒアリングします)

## 最後に
日数的に無理な場合、リスケします。早めにアラートお願いします。
その場合、一緒に振り返って(何ができてて、何ができていないか)、改善していきましょう。
また、「○○までにできそう」なのかなど、見通しを教えてもらおうと思います。

よろしくお願いします。

**Comment by minako-nakanishi** [comment]
勉強の進捗報告はここに書いた方が良いですか？

**Comment by ikkyu-3** [comment]
Slackでお願いします！

**Comment by ghost** [comment]
ゴール決めてやった方がいいかもです。

**Comment by minako-nakanishi** [comment]
期限を決めてということですか？

**Comment by ghost** [comment]
期限もそうだけど、例えばチュートリアル終わったとか、練習で画面作ってみたとか、

**Comment by minako-nakanishi** [comment]
勉強した内容はSlackのopen _studyに載せてるよ。

**Comment by minako-nakanishi** [comment]
ゴール:再来週末までにQuickStartをやりきる

**Comment by ghost** [comment]
まぁそれはそれでやっててもらって。
このissueがずっと開きっぱだから、もし使ってないならクローズしてもいいんじゃない？

**Comment by minako-nakanishi** [comment]
上記ゴールを達成したらクローズします
