### ISSUE TITLE
Vagrant /ubuntu環境設定

### ISSUE THREAD

**Issue by yumtana2** [hr-js/sta_access_manager#68]
### 環境構築
- Vagrant / ubuntuの環境設定
 環境：Vagrant , Ubuntu17.04,
- Vagrant のGUI設定

### 親issue

- #58

**Comment by yumtana2** [comment]
https://github.com/hr-js/sta_access_manager/issues/58#issuecomment-362913999
実施中「Configuring grub-pc」の画面が出ず挫折。試したかったこともいまいち違ってて無念。

https://github.com/hr-js/sta_access_manager/issues/58#issuecomment-363508822
ちな、こっちはできてる気がします。

**Comment by krhrtky** [comment]
@yumtana2 
どんな画面が出るんだろう？
TerminalとVritual Box のキャプチャあったらみたい！

**Comment by yumtana2** [comment]
パスワードがわからなくてログインできない問題が発生してます。
これ確認しようとしたらなかった…！
[Vagrant box ubuntu/xenial64 の ubuntuユーザ の passwordについて](https://qiita.com/TKR/items/f27271c963de0033f7ff)

**Comment by krhrtky** [comment]
@yumtana2

username/Password : vagrant でログインできます。
#58 の記事↓参照
https://qiita.com/mhagita/items/8f339106c3b48eb098ca

**Comment by yumtana2** [comment]
- ubuntuログイン
↓
- ubuntu内のFFを起動
↓
- macがフリーズ
↓
- @krhrtky :ヘルプ強制再起動でおｋ・ @tankette148 :スペック確認しろ・ @yumtana2  :8GBだわ、4GB なわけｗｗ
↓
- 強制終了後スペック確認
↓
- **無事4GB で爆死**←いまここ

**Comment by yumtana2** [comment]
1. curlで疎通確認する。
　成功条件:httpステータス200で返却される、かつ、ページタイトルが返却された場合。
2. try-catchで安心安全なブラウザ起動する。
　ブラウザ起動するときにtry-catch入れる。

**Comment by ghost** [comment]
やってなさげなのでClose
