### ISSUE TITLE
ログの管理の検討

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#74]
## やりたいこと
- ログを取りたい。外部ファイル化
- サーバにファイルを送信(ftp?, 起動バッチで...)

**Comment by ghost** [comment]
@ikkyu-3 
これログってどんなログですか？

**Comment by ikkyu-3** [comment]
@kakaka19 
想定しているのは、ICカードスキャンしたログ？ぐらいですね。。
必要ないかもって思い始めてる感じです。

対応しないでcloseしていいと思いますが、どう思います？

**Comment by ghost** [comment]
@ikkyu-3 
必要ないと思っています。ラズパイにログ溜めても使い道があまり思いつきません(そもそものストレージの話とかあるし)。

**Comment by ikkyu-3** [comment]
@kakaka19 
了解！
対応しないのでcloseします
