### ISSUE TITLE
[管理画面]サーバーサイドの実装に向けて

### ISSUE THREAD

**Issue by Tchikawa** [hr-js/sta_access_manager#79]
・Node.js 超入門
　2章、3章、4章、5章1-3、7章

**Comment by krhrtky** [comment]
@Tchikawa 
## キャッチアップで意識してほしいこと

1. Node.jsの基本的な書き方

   ブラウザのjavascriptと異なる点(require, http, npm or yarn)
   
2. [Express](http://expressjs.com/ja/) (Node.jsのアプリケーションフレームワーク)の書き方

   Nodeでサーバサイドを作る時のデファクト

   今回使用する [Fastify](https://www.fastify.io/) も書き方は互換性があるので重要。

3. 調べても分からなかったら聞きましょう

   - 何がしたいことか

   - したいこととどう違うのか

   - どう調べたのか

   - どの辺りが原因っぽいのか

   をまとめてから聞くとGood

**Comment by Tchikawa** [comment]
4章までOK!

**Comment by ghost** [comment]
ゴール決めてやった方がいいかもです。
