### ISSUE TITLE
[管理者側] APIの設計を行う

### ISSUE THREAD

**Issue by nekonogeboku** [hr-js/sta_access_manager#80]
- APIの設計つめる
 - @Tchikawa に共有

**Comment by ghost** [comment]
APIの設計そのものよりも、どんな目的で何を書くかをまずは検討してほしい

- 何をするAPIか？
- 何のために書くのか？
    - 実装の共有をしやすくして、属人化を防ぐ
    - 記録として残しておく
    - 実装予定のものをドキュメントにして、他の人にレビューしてもらうためetc...
- 図は必要か?
    - シーケンス図とかはあると実装がわかりやすい。しかし手間。
- 文章だけで良いか?

**Comment by nekonogeboku** [comment]
後ほど修正追記しますメモ
メソッド, URL, Data, JSON, status


機能
---

### 処理失敗(共通)

status: 500

```json
{
    "error":{
        "message": "サーバが正常に稼働していません。管理者にお問い合わせください。"
    }
}
```

### ログイン

__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/login |
| method | GET |

__Request__
 
__Response__

#### ログイン画面取得

status: 200

`login.html`


__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin |
| method | POST |

__Request__

Content-Type: application/json

```json
{
    "id": "xxxxxxxxx",
    "password":"xxxxxxxxx"
}
```

__Response__

#### ログイン成功

status: 200
`index.html`

form送る
失敗した場合`/login`へリダイレクト（クエリにエラーメッセージセット）


### 目的画面表示
**_クエリの有無で挙動を変更します。_**

- クエリなし
クエリがない場合、データのある直近の日付データ1日分を取得
取得データのソート順は
1. 現在いるか、いないか
1. 日時(来た順)
1. 日付(新しい順)


__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/purpose |
| method | GET |

__Request__
（なし）
__Response__
status: 200

```json
[{
    "name":"xxxxxxxxx",
    "mail":"xxxxxxxxx",
    "purpose":"勉強会 or サークル or XXXX or XXXX",
    "loginDate":"yyyy-mm-dd",
    "isEntry":"boolean型"
},{}]
```

- クエリあり
クエリで日付があった場合は期間の指定をしているので、期間のデータ取得
取得データのソート順は
1. 現在いるか、いないか
1. 日時(来た順)
1. 日付(新しい順)


__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/purpose |
| method | GET |

__Request__
?from=yyyy-mm-dd&to=yyyy-mm-dd

__Response__
status: 200

```json
[{
    "name":"xxxxxxxxx",
    "mail":"xxxxxxxxx",
    "purpose":"勉強会 or サークル or XXXX or XXXX",
    "loginDate":"yyyy-mm-dd",
    "isEntry":"boolean型"
},{}]
```

#### 更新

__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/purpose |
| method | PUT |

__Request__

Content-Type: application/json

```json
[{
    "mail":"xxxxxxxxx",
    "purpose":"勉強会 or サークル or XXXX or XXXX",
    "loginDate":"yyyy-mm-dd",
    "isEntry":"boolean型"
},{}]
```

__Response__

#### 更新成功
status: 200


#### 削除

__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/purpose |
| method | DELETE |

__Request__

Content-Type: application/json

```json
[{
    "mail":"xxxxxxxxx",
    "loginDate":"yyyy-mm-dd",
},{}]
```

__Response__

#### 削除成功
status: 200



### グラフ
__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/graph |
| method | GET |

__Request__

__Response__
status: 200

```json
[{
"date":"yyyy-mm-dd",
"work":"number",
"study":"number",
"meetUp":"number",
"circle":"number"
},{}]
```
ソート：日付(開放日＝該当データがある日付) 昇順

### ユーザ一覧画面表示
**_クエリの有無で挙動を変更します。_**

- クエリなし
クエリがない場合、全データ取得
データはメールアドレス昇順で取得

__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/users |
| method | GET |

__Request__
(なし)

__Response__
status: 200

```json
[{
    "name":"xxxxx",
    "mail":"xxxxx",
    "id":"xxxxx",
    "loginDate":"yyyy-mm-dd",
},{}]
```
- クエリあり
クエリで日付があった場合、期間内にログインしたユーザデータを取得
データはメールアドレス昇順で取得
__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/users |
| method | GET |

__Request__
?from=yyyy-mm-dd&to=yyyy-mm-dd

__Response__
status: 200

```json
[{
    "name":"xxxxx",
    "mail":"xxxxx",
    "id":"xxxxx",
    "loginDate":"yyyy-mm-dd",
},{}]
```


#### 更新

__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/users |
| method | PUT |

__Request__

Content-Type: application/json

```json
[{
    "name":"xxxxx",
    "mail":"xxxxx",
    "id":"xxxxx",
},{}]
```

__Response__

#### 更新成功
status: 200


#### 削除

__I/O__

| name   | value  |
| ------ | ------ |
| API    | /admin/users |
| method | DELETE |

__Request__

Content-Type: application/json

```json
[{
    "name":"xxxxx",
    "mail":"xxxxx",
    "id":"xxxxx",
},{}]
```

__Response__

#### 削除成功
status: 200

**Comment by nekonogeboku** [comment]
めも ちょっともらった意見とかまとめときます
- セキュリティ周りどうするか
- ログイン別にする？
- 全部〜/adminついてるけどいらないのでは？

詳細土曜とかに詰める感じで

**Comment by nekonogeboku** [comment]
本日中に確認してもらい、問題なければwikiへ反映します

**Comment by nekonogeboku** [comment]
今後変更があった際には別issueで対応する

**Comment by Tchikawa** [comment]
確認しましたのでクローズします

**Comment by ghost** [comment]
これAPIの話じゃなくて、画面のURLの話じゃね？と思ったんすけど、気になったところを書いておきます。

### 全体

- htmlやformなど、画面部品にまで言及している部分があります。APIとしては特に必要のない情報なので、削除してください。
- URLに`/admin/xxx`とありますが、`管理者側のAPI`として区別するだけの識別子は必要ありません。利用者側、管理者側で共通して使用するAPIの場合、それぞれ`/admin/~`、`/user/~`と冗長になってしまいます。
- 更に言えば`/admin/users`とかは管理者権限を持つユーザなのか、管理されているユーザなのか、パスからは判断できません。

### APIごと
####  ログイン,ログイン画面取得
- 単純な画面遷移だと思うので、APIは必要ありません。画面側でルーティングを行ってください。
- 認証に関しては別に切り出したいので、一旦保留にしてください

#### 目的画面表示
#### ユーザ一覧画面表示
> クエリの有無で挙動を変更します。

クエリの有無で挙動を変更する理由が若干わかりません。

#### グラフ
- `graph`というpath自体、画面側の実装を意識したものになっています。レスポンスでグラフを返すわけではないですよね？画面でグラフを作成する場合に必要な情報は何か？といった感じでAPIを決めてください。

**Comment by ikkyu-3** [comment]
修正が必要なので、openに戻します。

**Comment by nekonogeboku** [comment]
- URLの/admin/~
本日の話し合いで、管理側を別アプリに切り出しを検討したい案が出たため一旦相談
/admin~は現時点でのAPIサーバーとURLが競合する可能性があったためつけていたが、
指摘より/admin部分は削除で対応

 - ログイン,ログイン画面取得
>単純な画面遷移だと思うので、APIは必要ありません。画面側でルーティングを行ってください。
画面遷移は削除で対応、別issueでルーティング設計します 。
>認証に関しては保留
保留します こちらも別issue作成します。

- 目的画面
from toが省略された場合は
デフォルトの検索条件(ページの初期表示に使用)
・直近で入室記録がある日付の1日分のデータを返す
（直近のデータのある日はフロントで判断できないので、クエリを送信しない）
from-toクエリは検索時に使用予定
を想定してます。

 - ユーザ一覧画面表示
from toが省略された場合は
デフォルトの検索条件(ページの初期表示に使用)
・クエリがない場合、全ユーザデータ取得
from-toクエリは検索時に使用予定
を想定してます。

- グラフ
/graph →変更します
/total/users/purpose(グラフ)

追加予定
/total/users
ユーザそれぞれの統計情報返す

**Comment by ghost** [comment]
かなり悩んでるんですが。ユーザの更新・削除のAPIは提供しない方がいいのではないかと思いました。

管理者側の要求にはありませんし、提供するのであれば、認証周りをかなりしっかり検討する必要があると思っています。

**Comment by ikkyu-3** [comment]
> ユーザの更新・削除のAPIは提供しない方がいいのではないかと思いました。

確かに管理画面案でこちら側で追加した機能なので、要求ではないです。
管理者ならユーザの更新・削除は必要かなと思い、とりあえず入れてみたという感じです。

今後追加実装となる可能性はあると思いますので、
個人的にはAPIの設計は残しておいて、**今回、ユーザの更新・削除のAPIは提供しない** というのがいいかなと思います。

認証周りの検討もそうなのですが、
開発期間を考えると、最近管理画面の実装する機能が多いような気がしています。

@tankette148 
意見などあれば聞かせて欲しいです。

**Comment by nekonogeboku** [comment]
確認したところ「削除、更新機能自体をなくす」とのことでしたので、
ページについては一部変更した方がいいかと思いました。
こうなるとメインはデータを見ることになるので、
一覧ページの合体かグラフと一覧合体あたりしちゃっていいんじゃないかと思ってます。

**Comment by ghost** [comment]
@ikkyu-3 
>管理者ならユーザの更新・削除は必要かなと思い、とりあえず入れてみたという感じです。

まぁCRUD全て実装する必要もないので、要求になければいいかなと思っています。  
管理者っていっても、実際DBの運用までやってくれるかと言ったら微妙な気もするので。

>開発期間を考えると、最近管理画面の実装する機能が多いような気がしています。

グラフ表示とかはHighchartsの仕様に依存するかと思いますんで、モックは端折ってもいいと思います。

**Comment by ghost** [comment]
一応できました

### 処理失敗(共通)

status: 500

```json
{
    "error":{
        "message": "サーバが正常に稼働していません。管理者にお問い合わせください。"
    }
}
```

### 入室記録取得

__I/O__

| name   | value  |
| ------ | ------ |
| API    | /users |
| method | GET    |

__Request__

| key       | value    |
| --------- | -------- |
| date.from | yyyymmdd |
| date.to   | yyyymmdd |

__Response__

status: 200

```json
    [
        {
            "mail": "ta-low@hoge.ne.jsp",
            "name": "hoge",
            "purpose": "work or study or meetUp or circle or other",
            "isEntry": "true/false",(boolean)
            "workspace": {
                "entry": "入室時刻",(long)
                "exit": "退室時刻(しているなら)"(long)
            }
        },{
            ....
        }
    ]
```


### 直近の入室記録取得

__I/O__

| name   | value         |
| ------ | ------------- |
| API    | /users/recent |
| method | GET           |


__Request__

なし

__Response__

status: 200

```json
    [
        {
            "mail": "ta-low@hoge.ne.jsp",
            "name": "hoge",
            "purpose": "work or study or meetUp or circle or other",
            "isEntry": "true/false",(boolean)
            "workspace": {
                "entry": "入室時刻",(long)
                "exit": "退室時刻(しているなら)"(long)
            }
        },{
            ....
        }
    ]
```


### 集計(目的別)

__I/O__

| name   | value               |
| ------ | ------------------- |
| API    | /total/user/purpose |
| method | GET                 |

__Request__

| key        | value    |
| ---------- | -------- |
| sort.key   | date     |
| sort.order | desc/asc |

__Response__
status: 200

```json
[
    {
        "date": "yyyymmdd",(date)
        "purpose" :{
            "work": 19,(integer)
            "study": 20,(integer)
            "meetUp": 30,(integer)
            "circle": 40s(integer)
        }
    },
    {
        ...
    }
]
```

**Comment by Tchikawa** [comment]
ありがたや...

**Comment by nekonogeboku** [comment]
@kakaka19 まとめてくださってありがとうございます、内容確認しました!
問題ないと思います、
これで一旦コミットして、今後足りない等あった際には追加していく形にしたいと思います。

wiki作成後にこのissueを閉じたいと思います。

**Comment by nekonogeboku** [comment]
@kakaka19 
[API](https://github.com/hr-js/sta_access_manager/wiki/api)
ここに追記予定ですが、重複ありそうなので後ほど相談してから追記したいと思います。

**Comment by nekonogeboku** [comment]
追記完了

**Comment by ghost** [comment]
TOC(目次)も追加すること。

**Comment by nekonogeboku** [comment]
すみません、閉じてませんでした。
目次追記完了　今後は別issueで対応します。
