### ISSUE TITLE
Ubuntu/Dockerでステージング環境の構築

### ISSUE THREAD

**Issue by ghost** [hr-js/sta_access_manager#83]
### 目的
Ubuntu(Vagrant) + Dockerでステージング環境を構築する

### 概要
本番環境と同じUbuntuOS上でAPIが動作するコンテナを作成する

### ゴール
- Vagrantでの仮想マシン(Ubuntu)作成
- 仮想マシンにDocker導入
- #82 で作成したimageを使って、APIが動作するか確認。動作しなければimageを修正。
- 修正したimageが本番環境で使えるか確認。

**Comment by krhrtky** [comment]
これはVMWareからむと変わってくる話？変わらず？

**Comment by ghost** [comment]
変わらないよ。

**Comment by krhrtky** [comment]
承知です

**Comment by ghost** [comment]
dockerで環境できたのでclose
