### ISSUE TITLE
[管理者]　管理者用のアプリケーション切り離し 

### ISSUE THREAD

**Issue by Tchikawa** [hr-js/sta_access_manager#90]
cc:@kakaka19 

指摘
・APIのURL設計なのに静的ファイルの機能もある
・serverの役割が増える→構成が変わる
**・webappに切り出して役割を分ける**

**Comment by ghost** [comment]
利用者側API同様、https://github.com/hr-js/sam_api_server に実装を行う。切り離しは行わないので、クローズ。
