### ISSUE TITLE
管理者側API実装

### ISSUE THREAD

**Issue by ghost** [hr-js/sta_access_manager#94]
@Tchikawa

何をやってるのかが、あまり見えてこないので、記載お願いします！

実装するAPIはいくつあるか？
どの様なことが課題か？

まぁあとは書けること。

**Comment by Tchikawa** [comment]
https://github.com/hr-js/sta_access_manager/wiki/api
ここの、管理画面側使用以下の3つを実装予定です。
といあえず、schemaだけ作って、krhrtkyに見てもらいました。

・あんまり理解できてないこと
　ikkyu-3に教えてもらったりkrhrtkyに聞いたりしてます！
　土曜開放デーで終わらせたい

**Comment by Tchikawa** [comment]
@kakaka19 
ご報告
shema、manegiment.js修正してpushしました。
申し訳ありませんが、ElasticserchのDAO投げても大丈夫でしょうか？

新たに、schemaのバリデーションをどこまでかけるかが決まってない問題が出たので、別でissue立てて@tankette148と話会います。

**Comment by ghost** [comment]
@Tchikawa 
お疲れ様でした。4月中に対応します。
あとプルリク投げてください

**Comment by Tchikawa** [comment]
@kakaka19 
ありがとうございます！
これ、DAO呼ぶところ適当に名前つけてやっちゃってるんだけどプルリク投げちゃって大丈夫なの..??

**Comment by ghost** [comment]
コメントみてなかった。取り敢えずdao呼ばないでください。

**Comment by ghost** [comment]
実装終わったのでClose
