### ISSUE TITLE
[確認][API] ElasticSearchの設定

### ISSUE THREAD

**Issue by krhrtky** [hr-js/sta_access_manager#95]
@kakaka19 

APIを起動しようとしたときにいくつか、上手くいかない部分があったので確認です。

1.  ElasticSearchのポート

- デフォルトのポートは`9200` だけど、 `routes/users.js` では `9400` で書かれている(10行目)。

```javascript
module.exports = async function(fastify, opt, next) {
  const provider = require('./provider')('localhost', 9200);
  const handler = (response, reply) => {
    if (response.code === 1) {
      reply.code(400).send(response);
    }
    reply.send(response);
  };

```

1. 起動時の前提

- ElasticSearchは別途立ち上げておかないと接続できないですよね。

  => RDB考えてみれば、当然だけど....

**Comment by ghost** [comment]
コードには一応9200としてるけと。。。

**Comment by krhrtky** [comment]
ほんとだ。何かの拍子にローカル書き換えちゃったかな。
なんでもないです。。。

**Comment by ghost** [comment]
まぁ設定を外部化した方がいいのかもね。

**Comment by krhrtky** [comment]
確認狩猟しているのでclose
