### ISSUE TITLE
【Raspberry Pi】ディレクトリ構成を検討

### ISSUE THREAD

**Issue by ikkyu-3** [hr-js/sta_access_manager#96]
## React+Reduxのディレクトリ構成を検討
ディレクトリ構成を考えてみました。
ざっと考えたディレクトリ構成です。
### 案1
見本にしたディレクトリ構成
[redux/examples/todos/src at master · reactjs/redux](https://github.com/reactjs/redux/tree/master/examples/todos/src)

```
./
    app/
        actions/
        components/
        containers/
        reducers/
        saga/
        modules/
        rootRouter.jsx  //  containerをまとめたファイル + react-router実装
        index.jsx  //  ReactDOM.renderを呼び出すファイル
    test/
        actions/
        components/
        containers/
        reducers/
        saga/
        modules/
        index.test.jsx
```
#### メリット
- 各フォルダ内がどんな役割のファイルがあるかわかりやすい
#### デメリット
- 各フォルダ内のファイル数が増えると管理がしづらい
### 案2
- 修正しました(3月27日時点)
```
.
├── components/
│   ├── App.jsx  // containerをまとめたファイル + react-router実装
│   ├── rootReducer.jsx  // reducerをまとめたファイル
│   ├── button/
│   │   ├── button.css  // css
│   │   ├── button.jsx  // jsxファイル
│   │   └── button.test.jsx
│   ├── exit/
│   │   ├── exit.css  // css
│   │   ├── exit.jsx  // jsxファイル
│   │   ├── exit.test.jsx
│   │   ├── exitAction.js  // action
│   │   ├── exitAction.test.js
│   │   ├── exitContainer.js  // container
│   │   ├── exitContainer.test.js
│   │   ├── exitReducer.js  // reducer
│   │   └── exitReducer.test.js
│   ├── layout/
│   ├── not-exist/
│   ├── participants/
│   ├── purpose/
│   ├── register/
│   └── sideber/
├── index.jsx  //  ReactDOM.renderを呼び出すファイル
├── modules/
└── saga/
```
#### メリット
- フォルダ毎にtestまで完結しているので管理がしやすい
#### デメリット
- ファイルの命名規則など、事前に決めておく必要がある

案1で実装した経験としては、ファイル数が増えてくると、管理しづらさがあります。

案2は管理がしやすそうなので、このディレクトリ構成でやってみようかなって思ってます。

**Comment by ghost** [comment]
@ikkyu-3 

案２だとページでディレクトリ切ってるのか画面部品ごと切ってるのかちょっとわからなくないですか？

>フォルダ毎にtestまで完結しているので管理がしやすい

複数のページで再利用されているcontainerがあった場合（例えばbuttonContainer.jsとかそうじゃないですかね）、テストコードが重複して、変更の際に逆に管理が大変になりそうな気もします。

**Comment by ikkyu-3** [comment]
> 案２だとページでディレクトリ切ってるのか画面部品ごと切ってるのかちょっとわからなくないですか？

buttonやiconなどの名前だと画面部品だなと直感的だと思ったんだけど。
そしたら、
```
components/
    pages/
    modules/(parts?)
```
というのはどうでしょう？

> 複数のページで再利用されているcontainerがあった場合（例えばbuttonContainer.jsとかそうじゃないですかね）、テストコードが重複して、変更の際に逆に管理が大変になりそうな気もします。

あ、申し訳ない。
ちょっと書き方が悪かったので補足しておくと、画面部品はjsxとcssファイルのみ作成する方針で考えています。
container.jsはページごとにcontainerやaction, reducerを作成します。

↑修正しておきます

**Comment by ikkyu-3** [comment]
## React+Reduxのディレクトリ構成以外のディレクトリ構成
チャットで話した内容をここに記載しておきます。

- React+Redux以外のディレクトリ構成以外が混沌としている
- こちらのディレクトリ構成も考えた方がよいのではないか

ということで、一度考えたいと思います。

**Comment by ikkyu-3** [comment]
mergeしたのでcloseします。
