### ISSUE TITLE
[api] [test] jest でエラーが発生して実行できない

### ISSUE THREAD

**Issue by krhrtky** [hr-js/sta_access_manager#98]
## 事象

- `jest` で `require()` のグローバルメソッドが呼び出せない

    ```
    // エラーメッセージ
    TypeError: require(...) is not a function
    ``` 

- ググるも原因分からず(babelっぽい)

- `jest` のチュートリアルは実行できる( `require()` を読み込めている )ので、jest自体が原因か切り分けできず。

- とりあえず、状況報告まで

**Comment by ghost** [comment]
requireできなかったモジュールはなんですか？

**Comment by krhrtky** [comment]
fastify です

**Comment by ghost** [comment]
エラーでた時の環境と、どんなコードを実行しようとしたら起きたのか教えてほしい。

**Comment by krhrtky** [comment]
- 下記、ソースを実行。

- コマンド

`NODE_HTTP=http jest` をnpm scriptで実行

-  node -v

    v9.4.0

- server.js

```javascript
'use strict';↲
const fs = require('fs');↲
const path = require('path');↲
const getOpt = () => {↲
  switch (process.env.NODE_HTTP) {↲
  case 'http2':↲
    return {↲
      http2: true,↲
      https: {↲
        key: fs.readFileSync(path.join(__dirname, '.', 'https', 'cakey.pem')),↲
        cert: fs.readFileSync(↲
          path.join(__dirname, '.', 'https', 'cacert.pem')↲
        ),↲
        passphrase: 'xxxxx',↲
      },↲
      logger: true,↲
    };↲
  default:↲
    return {↲
      logger: true,↲
    };↲
  }↲
};↲
↲
const buildServer = () => {↲
  const fastify = require('fastify')(getOpt());↲
  fastify.register(require('./routes/users'), { logLevel: 'debug' });↲
  return fastify;↲
};↲
↲
module.exports = buildServer;↲

```

- server.test.js

```javascript
const fastify = require('./server')();

test('test', () => {
    fastify.inject(
      {
        method: 'GET',
        url: '/test',↲
      },↲
      response => {
      console.log(err);
      console.log(response.statusCode);
      }
    );
    fastify.close();
  });↲
````

情報足らなければ、指摘よろしくです。

**Comment by ghost** [comment]
server.jsとserver.test.jsは同じディレクトリ？

**Comment by kakaka19** [comment]
```js
module.exports = buildServer;
```
でexportsしてるから、
```js
const buildServer = require('./server')();
```
じゃないといけないと思う。

**Comment by ghost** [comment]
そもそも`yarn run http`,`npm start http`,`node server.js`で動いてないみたいです。

**Comment by ghost** [comment]
なんかshema.jsでtypoがあったんでfixしてdevelopにpushしました。
多分これで大丈夫だと思う。

**Comment by krhrtky** [comment]
やり直したけど、同じエラーメッセージでないすか？

**Comment by ghost** [comment]
jestの方では試してないっす。developからの差分pullした？

**Comment by ghost** [comment]
branch切って、pushした方がいいかも。同じコードで試してみる。

**Comment by krhrtky** [comment]
schema.jsをdevelopからコピーして実行したから間違いないはず

**Comment by ghost** [comment]
まぁbranch切って一旦pushしてもらっていいすか。自分で書いてもいいけど、違ったらまた手間なんで。

**Comment by kakaka19** [comment]
原因はserver.jsで同期を待たずに(awaitせずに)requireしていたためです。修正をrouter_testにコミットしたので確認してください。
差分貼っときます。https://github.com/hr-js/sam_api_server/commit/28cba5e7920be8184f8cb58e6bd30135395ca3f6

**Comment by ghost** [comment]
@krhrtky 

原因はserver.jsで同期を待たずに(awaitせずに)requireしていたためです。修正をrouter_testにコミットしたので確認してください。
差分貼っときます。https://github.com/hr-js/sam_api_server/commit/28cba5e7920be8184f8cb58e6bd30135395ca3f6

**Comment by ghost** [comment]
あと多分この修正をすると起動できなくなるので...適宜調整してください

**Comment by krhrtky** [comment]
@kakaka19 
調査、対応ありがとう！助かりますm(_ _)m

これでテストコードはかけるはずなので、今週末にでも担当のAPIで正常系の処理は書くようにします。
あと、ESLintがJestに対応してないからプラグイン入れてみてプルリク出します。

@Tchikawa 
`router_test` ブランチのテストコードを参考に書き始めてみて。
確認する中身とかは全然書かれてないけど、そのへんは想像で。

**Comment by krhrtky** [comment]
@kakaka19 @Tchikawa 

jestのエラー解消しました。
原因は、関数内でreqiureが使用できなかったようです。
routes/users.jsのproivderを読み込み処理がそうなっていました。
なので、トップレベルに上記処理を移行しました。
あとは、jestのリファレンスにそってテストコードを書いていけば大丈夫です！
